import { useEffect, useState, type MouseEvent } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowUpRight, ArrowRight, X, Menu, Github, Linkedin, ArrowDown, Layers, Braces, Workflow, Check, ExternalLink } from 'lucide-react';
import MetroHero from '@/components/ui/scroll-locked-video-hero';
import { projects, experience, skills, asset, github, linkedin, type Project } from './data';

function OutLink({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}) {return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={17}/></a>;}
function MarketVisual() {return <div className="market-visual" aria-label="Illustration of MarketTrade decision diagnostics"><div className="terminal-top"><span>MARKET<span className="accent">TRADE</span></span><span className="terminal-dot">● SYSTEM CHECK</span></div><div className="chart-lines"><span/><span/><span/><span/><span/><div className="chart-path"/></div><div className="decision"><span>DECISION ENGINE</span><b>REASONING,<br/>MADE VISIBLE.</b><div><Check size={14}/> Risk validation <Check size={14}/> Decision history</div></div><small>ILLUSTRATIVE PROJECT VISUAL</small></div>;}
function ProjectArt({project}:{project:Project}) {return project.image?<img src={asset(project.image)} alt={`${project.name} website interface`} loading="lazy"/>:<MarketVisual/>;}
export default function App() {
  const [filter,setFilter] = useState('All work');
  const [selected,setSelected] = useState<Project|null>(null);
  const [menu,setMenu] = useState(false);
  const [active,setActive] = useState('home');
  useEffect(()=>{
    const observer = new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);}),{rootMargin:'-20% 0px -55% 0px'});
    document.querySelectorAll('main > section[id]').forEach(s=>observer.observe(s));
    return ()=>observer.disconnect();
  },[]);
  const go = (event:MouseEvent<HTMLAnchorElement>,id:string) => {
    event.preventDefault();setMenu(false);window.dispatchEvent(new Event('portfolio:navigate'));
    requestAnimationFrame(()=>{document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});history.replaceState(null,'',`#${id}`);});
  };
  return <>
    <a href="#work" className="accessibility-skip" onClick={e=>go(e,'work')}>Skip to selected work</a>
    <header className="site-header"><a href="#home" className="wordmark" onClick={e=>go(e,'home')}>jevin<span>thakar.</span><i>JT</i></a><nav aria-label="Main navigation" className={menu?'nav open':'nav'}>{[['work','Work'],['about','About'],['experience','Experience']].map(([id,label])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={e=>go(e,id)}>{label}</a>)}<a className="nav-contact" href="#contact" onClick={e=>go(e,'contact')}>Let’s talk <ArrowUpRight size={15}/></a></nav><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
    <main>
      <section id="home"><MetroHero/></section>
      <section className="intro wrap" aria-label="What I do"><div className="eyebrow"><span className="live-dot"/>AHMEDABAD, INDIA · OPEN TO PROJECTS</div><div className="intro-grid"><h2>Interfaces with <em>character.</em><br/>Software with <em>purpose.</em></h2><div><p>I’m Jevin, a web/UI designer and full-stack developer. I bring visual ideas to life through immersive websites, useful applications and conversational AI.</p><a className="text-link" href="#work" onClick={e=>go(e,'work')}>A few things I’ve built <ArrowDown size={18}/></a></div></div><div className="discipline-line"><span>DESIGN</span><i>↗</i><span>DEVELOPMENT</span><i>↗</i><span>AI EXPERIENCES</span></div></section>
      <section id="work" className="work-section wrap"><div className="section-top"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, made <em>real.</em></h2></div><span className="section-aside">A selection of applications<br/>and digital experiences.</span></div><div className="filter-row" role="group" aria-label="Filter projects">{['All work','AI & applications','Web experiences'].map(f=><button className={filter===f?'selected':''} key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}<span>{f==='All work'?projects.length:projects.filter(p=>p.category===f).length}</span></button>)}</div>
      <div className="project-grid">{projects.filter(p=>filter==='All work'||p.category===filter).map((p,index)=><article key={p.id} className={`project-card ${p.theme}`}><button className="project-image" onClick={()=>setSelected(p)} aria-label={`View ${p.name} case study`}><div className="project-corner">{p.category==='AI & applications'?'APPLICATION':'WEB EXPERIENCE'}</div><ProjectArt project={p}/><div className="project-open"><ArrowUpRight size={24}/></div>{p.id==='jinha'&&<div className="jinha-overlay"><span>JINHA</span><small>VOICE. PRESENCE. CONNECTION.</small></div>}</button><div className="project-info"><span className="project-number">0{index+1}</span><div><p className="eyebrow">{p.label}</p><h3>{p.name}</h3><p>{p.summary}</p><div className="tag-row">{p.tags.slice(0,4).map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><button className="text-link" onClick={()=>setSelected(p)}>Inside the project <ArrowRight size={16}/></button><OutLink href={p.live}>Live {p.id==='jinha'?'interface':'website'}</OutLink></div></div></div></article>)}</div>
      <div className="archive"><p>Before this chapter.</p><span>My previous 3D portfolio is still available.</span><OutLink href="https://jevin042.github.io/portfolio-3d/">Visit the archive</OutLink></div></section>
      <section id="about" className="about-section"><div className="wrap about-grid"><div className="about-visual"><div className="monogram">j<span>t</span><b>.</b></div><span className="orbit-label">DESIGN THINKING / ENGINEERING MINDSET</span><div className="about-coordinate">23.0225° N<br/>72.5714° E<br/><small>AHMEDABAD, INDIA</small></div></div><div className="about-copy"><p className="eyebrow">02 / A LITTLE CONTEXT</p><h2>Curiosity leads.<br/><em>Craft follows.</em></h2><p>I work across interface design and implementation. That means shaping how a product looks and feels, then building the frontend, integrations and backend services that make it work.</p><p>My work spans business websites, internal dashboards, workflow automation and immersive digital experiences. Recently, I completed Jinha, an independent AI voice and avatar companion.</p><p>I’m interested in work where thoughtful design meets a practical problem—and where the finished product is useful enough to keep using.</p><OutLink href={linkedin} className="text-link">More about my background</OutLink></div></div><div className="wrap skills-grid">{skills.map((group,i)=>{const Icon=[Layers,Braces,Workflow][i];return <div key={group.title}><Icon size={23}/><p className="eyebrow">0{i+1} / CAPABILITIES</p><h3>{group.title}</h3><div className="skill-tags">{group.items.map(item=><span key={item}>{item}</span>)}</div></div>;})}</div></section>
      <section id="experience" className="experience-section wrap"><div className="section-top"><div><p className="eyebrow">03 / THE JOURNEY</p><h2>Built through <em>doing.</em></h2></div><OutLink href={linkedin} className="text-link">View LinkedIn</OutLink></div><div className="experience-list">{experience.map((job,i)=><article className="experience-row" key={job.company+job.date}><div className="experience-date"><span>0{i+1}</span>{job.date}</div><div><h3>{job.company}</h3><h4>{job.role}</h4></div><p>{job.body}</p></article>)}</div><div className="education"><span className="eyebrow">EDUCATION</span><h3>Bachelor of Computer Engineering</h3><p>Apollo Institute of Engineering and Technology · Grade 9.6/10</p></div></section>
      <section id="contact" className="contact-section"><div className="wrap"><div className="eyebrow"><span className="live-dot"/>04 / NEXT, SOMETHING WORTH BUILDING</div><h2>Have an idea?<br/>Let’s give it <em>form.</em><ArrowUpRight className="contact-arrow"/></h2><div className="contact-bottom"><p>Web / UI design. Full-stack applications.<br/>Interactive experiences. Conversational AI.</p><div className="contact-links"><OutLink href={linkedin}><Linkedin size={20}/>Connect on LinkedIn</OutLink><OutLink href={github}><Github size={20}/>Explore GitHub</OutLink></div></div></div></section>
    </main><footer className="wrap"><span>© {new Date().getFullYear()} Jevin Thakar</span><span>Designed with intent. Built to work.</span><a href="#home" onClick={e=>go(e,'home')}>Back to top ↑</a></footer>
    <Dialog.Root open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="case-study" aria-describedby="case-summary"><Dialog.Close className="modal-close" aria-label="Close project"><X size={22}/></Dialog.Close>{selected&&<><div className={`case-image ${selected.theme}`}><ProjectArt project={selected}/></div><div className="case-content"><p className="eyebrow">{selected.label}</p><Dialog.Title>{selected.name}</Dialog.Title><h3>{selected.headline}</h3><Dialog.Description id="case-summary">{selected.summary}</Dialog.Description><div className="tag-row">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><h4>What I built</h4><ul>{selected.details.map(detail=><li key={detail}>{detail}</li>)}</ul>{selected.id==='jinha'&&<img className="live-screenshot" src={asset('jinha-live.png')} alt="Jinha live portrait conversation with captions and microphone controls"/>}{selected.note&&<p className="case-note">{selected.note}</p>}<div className="case-links"><OutLink href={selected.live} className="button-primary"><ExternalLink size={16}/>Explore live</OutLink>{selected.source&&<OutLink href={selected.source} className="button-secondary"><Github size={16}/>View source</OutLink>}</div></div></>}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </>;
}
