export const linkedin = 'https://www.linkedin.com/in/jevin-thakar-628871135/';
export const github = 'https://github.com/jevin042';
export const asset = (name:string) => `${import.meta.env.BASE_URL}images/${name}`;
export type Project = {id:string;name:string;category:'AI & applications'|'Web experiences';label:string;headline:string;summary:string;image?:string;theme:string;tags:string[];live:string;source?:string;note?:string;details:string[]};
export const projects:Project[] = [
  {id:'jinha',name:'Jinha Companion',category:'AI & applications',label:'INDEPENDENT PROJECT · SEPTEMBER 2026',headline:'A conversation with a little more presence.',summary:'A voice-first AI companion with live avatar conversation, multilingual replies and memory of recent turns.',image:'jinha-interface.png',theme:'jinha',tags:['React','TypeScript','Cloudflare','Supabase','Anam'],live:'https://jinha-companion.jinha-companion.workers.dev/',source:`${github}/jinha-companion`,note:'Interface is public. Conversations require an invited account and available provider credits.',details:['Designed the UI and built the React/TypeScript frontend, backend APIs and Cloudflare deployment.','Integrated Anam live portrait-avatar streaming with English, Korean and Spanish conversation, captions and microphone controls.','Implemented Supabase authentication, an invited-user allowlist, Durable Object memory and session budgets.','The full-length portrait is a still image; live portrait video is supplied by Anam. Type checking, 10 automated tests and production build passed.']},
  {id:'markettrade',name:'MarketTrade',category:'AI & applications',label:'INDEPENDENT APPLICATION · 2026',headline:'Decisions with visible reasoning.',summary:'An NSE swing-trading decision platform with risk validation, transparent diagnostics and persisted decision history.',theme:'market',tags:['Next.js','TypeScript','Supabase','Vercel'],live:'https://markettrade.vercel.app',note:'Independent software project. Source code is private. The application is a decision-support tool.',details:['Built and refined a rule-driven decision workflow with data checks, risk controls and explanations for candidate rejection.','Distinguished missing data, strategy rule blocks and rejected candidates so a NO_TRADE result has an actionable diagnostic cause.','Deployed the application with isolated Supabase infrastructure and verified live decision persistence in History.']},
  {id:'villa',name:'Villa Aurelia',category:'Web experiences',label:'PROPERTY WEBSITE · CONCEPT SHOWCASE',headline:'Architecture becomes an experience.',summary:'A cinematic property showcase with scroll-driven animation, responsive layouts and an interactive 3D model.',image:'villa.png',theme:'villa',tags:['Three.js','GSAP','Lenis','JavaScript'],live:'https://jevin042.github.io/villa-aurelia/',source:`${github}/villa-aurelia`,details:['Designed and built a premium property concept with large typography, editorial imagery and a scroll-led narrative.','Combined Three.js, GSAP and Lenis for model interaction, motion and smooth navigation.','Created responsive presentation across desktop and mobile. This is a concept showcase, not a claim of client employment.']},
  {id:'midnight',name:'Midnight Listening Room',category:'Web experiences',label:'INTERACTIVE MUSIC EXPERIENCE',headline:'A place to get lost in the music.',summary:'An interactive 3D listening room connecting a virtual environment with a YouTube music channel.',image:'midnight.png',theme:'midnight',tags:['Interactive 3D','JavaScript','YouTube'],live:'https://jevin042.github.io/midnight-listening-room/',source:`${github}/midnight-listening-room`,details:['Created an immersive browser interface combining music, storytelling and frontend design.','Integrated a YouTube channel into a spatial listening-room environment.']},
  {id:'aurum',name:'Aurum Evening',category:'Web experiences',label:'RESTAURANT WEBSITE · CONCEPT',headline:'An evening, translated into a website.',summary:'An immersive restaurant showcase with time-driven navigation and a custom flame cursor.',image:'aurum.png',theme:'aurum',tags:['JavaScript','Motion','Responsive UI'],live:'https://jevin042.github.io/aurum-evening/',source:`${github}/aurum-evening`,details:['Built an atmospheric restaurant concept combining visual storytelling with playful interaction.','Created time-driven navigation and a flame cursor as distinctive interface details.']},
  {id:'studio',name:'JA — Digital Studio',category:'Web experiences',label:'BUSINESS LANDING PAGE',headline:'Clarity with a point of view.',summary:'A responsive digital-studio landing page with clean visual hierarchy and a polished business presentation.',image:'studio.png',theme:'studio',tags:['HTML','CSS','JavaScript'],live:'https://jevin042.github.io/ja-studio/',source:`${github}/ja-studio`,details:['Designed and implemented a business landing page with consistent typography and responsive layouts.','Organized studio information into a clear browsing experience across desktop and mobile.']}
];
export const experience = [
  {date:'AUG 2026 — PRESENT',company:'Elefanto Agency',role:'Web Specialist',body:'Contribute to AI, software-product, automation and MVP projects, from early ideas through development and launch.'},
  {date:'SEP 2026 · COMPLETED',company:'Independent Project',role:'AI Application Developer — Jinha',body:'Designed, developed and deployed a voice/avatar companion with authentication, recent-turn memory and multilingual conversation.'},
  {date:'JAN 2025 — AUG 2026',company:'Elovet Design',role:'Software Developer',body:'Built internal web applications, operational dashboards, reporting tools, API integrations and desktop workflow utilities.'},
  {date:'AUG 2024 — NOV 2024',company:'Diamore Jewellery',role:'Full Stack Web Developer · Freelance',body:'Built a luxury jewellery e-commerce experience with responsive product pages, filtering, sorting and protected premium collections.'},
  {date:'MAR 2024 — AUG 2024',company:'Sandesh',role:'Hardware Network Engineer',body:'Supported hardware, servers and networks through troubleshooting, reliability and security work.'},
  {date:'SEP 2023 — NOV 2023',company:"Mum’s Kitchen",role:'Full Stack Web Developer · Freelance',body:'Created a responsive digital menu and ordering website with WhatsApp ordering, a gallery and inquiry forms.'}
];
export const skills = [
  {title:'Interface & experience',items:['Web / UI design','Responsive interfaces','Interactive 3D','Motion & visual storytelling','HTML / CSS','Tailwind CSS','Three.js / GSAP']},
  {title:'Applications & intelligence',items:['React / TypeScript','JavaScript','Conversational AI','Live avatar integration','Authentication','Conversation memory','Python / PHP']},
  {title:'Systems & delivery',items:['REST APIs','Workflow automation','Cloudflare Workers','Durable Objects','Supabase','MySQL','Git / deployment']}
];
